version: '3.9'

services:
  production:
    container_name: workspace-back
    image: workspace-back
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    env_file: .env
    environment:
      APP_ENV: production
      FLASK_DEBUG: 0
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - workspace-net
networks:
  workspace-net:
    driver: bridge