trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_CONTAINER_REGISTRY: 'ContenedorWorkspace'
  IMAGE_NAME: 'backend-caa'
  DOCKER_REGISTRY: '$(AZURE_CONTAINER_REGISTRY).azurecr.io'
  TAG: $(Build.BuildId)

jobs:
- job: BuildAndPush
  displayName: 'Build and Push Docker Image'
  steps:

    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        containerRegistry: '$(DOCKER_REGISTRY)'
        repository: '$(DOCKER_REGISTRY)/$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(TAG)'

    - task: AzureWebAppContainer@2
      displayName: 'Deploy to Azure Web App for Containers'
      inputs:
        appName: 'your-web-app-name'
        containerRegistry: '$(DOCKER_REGISTRY)'
        imageName: '$(DOCKER_REGISTRY)/$(IMAGE_NAME):$(TAG)'