name: Deploy Flask App to Azure

  on:
    push:
      branches:
        - main  # Ejecutar el workflow en cada push a la rama main

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:
      # 1. Configurar el repositorio
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Loguearse en Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: contenedorcaa.azurecr.io  # Cambia al servidor de tu ACR
          username: contenedorcaa  # Configura este secreto en GitHub
          password: ${{ secrets.AZURE_CONTAINER_PASSWORD }}

      # 3. Construir y empujar la imagen Docker
      - name: Build and push Docker image
        run: |
          docker build -t contenedorca.azurecr.io/flask-app:latest .
          docker push contenedorca.azurecr.io/flask-app:latest