name: Build and deploy container app to Azure Web App - BackendWorkspace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://contenedorcaa.azurecr.io/
        username: contenedorcaa
        password: ${{ secrets.AZURE_CONTAINER_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: contenedorcaa.azurecr.io/backend-caa:${{ github.sha }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BackendWorkspace'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: 'contenedorcaa.azurecr.io/backend-caa:${{ github.sha }}'